In [112]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [113]:
df = pd.read_csv("salary.csv")
df

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [114]:
from word2number import w2n

def word_to_num(s=None):
    try:
        return w2n.word_to_num(s)
    except ValueError:
        return 0

In [115]:
exp = df.experience.apply(lambda s: word_to_num(s))

In [116]:
df.experience = exp
df

experience  test_score  interview_score  salary
0           0         8.0                9   50000
1           0         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         NaN                7   72000
7          11         7.0                8   80000

In [143]:
import math

median_test_score = math.floor(df.test_score.median())
median_test_score

8

In [144]:
df.test_score = df.test_score.fillna(median_test_score)

In [145]:
lin_reg = linear_model.LinearRegression()

In [146]:
lin_reg.fit(df[["experience", "test_score", "interview_score"]].values, df.salary)

LinearRegression()

In [147]:
lin_reg.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [148]:
lin_reg.intercept_

17737.263464337688

In [149]:
lin_reg.predict([
    [2, 9, 6]
])

array([53205.96797671])

In [150]:
lin_reg.predict([
    [12, 10, 10]
])

array([92002.18340611])